### ISSUE TITLE
LIXA: No reference to  TX Transaction Demarcation specification in the page docs?

### ISSUE THREAD

**Issue by GitMensch** [tiian/tiian.github.io#1]
I've just happen to see that http://lixa.sourceforge.net mentions COBOL and documents that in http://lixa.sourceforge.net/lixa-doc/html/ch06.html but the tiian website doesn't.

Does this mean that COBOL is not supported any more or that the COBOL docs just not got converted / imported to the newer pages?
The samples are still in the repo: https://github.com/tiian/lixa/tree/master/doc/examples/cobol

**Comment by tiian** [comment]
Dear Simon,
thank for your feedback.
Nothing changed with respects of COBOL.
In the home page of LIXA [https://www.tiian.org/lixa/](https://www.tiian.org/lixa/) there's no explicit reference to COBOL because there's no explicit reference to the TX Transaction Demarcation specification. I might add it.
Some years ago I proposed an innovative interface named XTA (XA Transaction API) and I developed it only for C, C++, Python and Java. I didn't develop it for COBOL mainly because I'm not a COBOL expert at all and I would have probably create some useless stuff for real COBOL developers.
XTA was intended mainly for micro services architectures, but there would be no limitation in more traditional contexts.
The documentation you found in SourceForge is exactly replicated and maintained even in current web site: [https://www.tiian.org/lixa/manuals/html/ch06.html](https://www.tiian.org/lixa/manuals/html/ch06.html)
To reach it, just click on one of the two links in "Documentation" paragraph.

I have seen you opened some issues related to the LIXA project [https://github.com/tiian/lixa/issues](https://github.com/tiian/lixa/issuesl) : may I ask you what's the trigger of interest? It has been a long time I have not received feedback on this stuff.
If something is happening in COBOL ecosystem, please tell me something, I will appreciate.

About XTA for COBOL, that today doesn't exist, if someone inside the GNU COBOL community would like to implement it starting from the C version, I would be very happy to merge it.

All the best

**Comment by GitMensch** [comment]
The main reason is: I've stumbled over this when I had no notes available on how to link GnuCOBOL to Pro*COB processed sources, then inspecting the context and remembering that people said "this is missing for me", then inspect the docs how lixa can be used, ...
I really think that this project has some future in the (Gnu)COBOL ecosystem (otherwise I would not have put in the time for the stuff above).

> In the home page of LIXA https://www.tiian.org/lixa/ there's no explicit reference to COBOL because there's no explicit reference to the TX Transaction Demarcation specification. I might add it.

Ah, that's clear now - and of course I'd like to see the TX addition there, potentially with the COBOL reference.

I think it is reasonable to let some GnuCOBOL users check the XTA addition and can also think about some people that may want to implement that, given good documentation about it and the C side - we'll see.

**Comment by tiian** [comment]
I have made some rework on [LIXA](https://www.tiian.org/lixa/) page, your feedback will be appreciated.

**Comment by GitMensch** [comment]
Looks good to me.
